/*###############################################################
## MODULE: ontology.cpp
## VERSION: 1.0 
## SINCE 2015-10-30
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/


int main (int argn, char** argv) {
    
}
