/*###############################################################
## MODULE: relque.cpp
## VERSION: 1.0 
## SINCE 2015-10-13
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

using namespace std;
#include <iostream>
#include <vector>


int main (int argn, char** argv) {
    long N; // length of given string;
    // read from stdin 
    cin >> N;
    cout << "N: " << N << endl;
    if (N < 0) return -1;
    vector<long> T (N, 0);
    for (long i = 0; i < N; i++) {
        cin >> T[i];
        cout << T[i] << endl;
    }
    long Q1, Q2;
    while (cin >> Q1 >> Q2) {
        cout << Q1 << "-" << Q2 << endl;
    }
    

    // out to std
    }
