/*###############################################################
## MODULE: relque.cpp
## VERSION: 1.0 
## SINCE 2015-10-13
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

using namespace std;
#include <iostream>
#include <vector>


int main (int argn, char** argv) {
    long N; // length of given string;
    long K; // window size
    // read from stdin 
    cin >> N >> K;
    

    // out to std
    }
