/*###############################################################
## MODULE: 007_ReverseInteger.cpp
## VERSION: 1.0 
## SINCE 2015-10-23
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

class Solution {
public:
    int reverse(int x) {
        long max_int = 214748364;
        bool isNegative = x < 0? true:false;
        int remainder = x;
        if (isNegative) remainder = -1 * x;
        vector<int> digits;
        while (remainder > 0) {
            int cur = remainder % 10; 
            digits.push_back(cur);
            remainder /= 10;
        }
        int outcome = 0;
        int N = digits.size();
        for (int i = 0; i < N; i ++) {
            if (outcome > max_int) return 0;
            outcome = outcome * 10 + digits[i];
        }
        if (isNegative) outcome = -1 * outcome;
        return outcome; 
    }
};
