/*###############################################################
## MODULE: 038_CountAndSay.cpp
## VERSION: 1.0 
## SINCE 2015-10-23
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

class Solution {
public:
    string countAndSay(int n) {
        string prev = "1";
        for (int i = 2; i <= n; i++) {
            string cur = "";
            int len = prev.length();
            // if (len == 0) return "";
            int j = 1; 
            char value = prev.at(0);
            int count = 1;
            while (j < len) {
                char visited = prev.at(j);
                if (value == visited) 
                    count ++; 
                else {
                    // compoes new string
                    cur += to_string(count);
                    cur.push_back(value);
                    // refresh local data
                    value = visited; 
                    count = 1;
                }
                j++;
            }
            cur += to_string(count);
            cur.push_back(value);
            prev = cur;
        }
        return prev;
    }
};
