/*###############################################################
## MODULE: 046_Permutations.cpp
## VERSION: 1.0 
## SINCE 2015-10-23
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

class Solution {
    public:
    vector<vector<int> > result;
    vector<vector<int> > permute(vector<int> &num) {
        // Start typing your C/C++ solution below
        // DO NOT write int main() function
        permute(num, 0);
        return result;
    }
    
    void permute(vector<int> &num, int start)
    {
        if(start == num.size())
        {
            result.push_back(num);
        }
        for(int i = start; i < num.size(); ++i)
        {
            swap(num[i], num[start]);
            permute(num, start+1);
            swap(num[i], num[start]);
        }
    }
};
