/*###############################################################
## MODULE: 066_PlusOne.cpp
## VERSION: 1.0 
## SINCE 2015-10-23
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

class Solution {
public:
    vector<int> plusOne(vector<int>& digits) {
        int n = digits.size();
        int acc = 1;
        for (int i = n-1; i >= 0; i --) {
            int cur = digits[i] + acc;
            digits[i] = cur % 10;
            acc = cur / 10;
        }
        if (acc > 0)
            digits.insert(digits.begin(), acc);
        return digits;
    }
};
