/*###############################################################
## MODULE: 070_ClimbingStairs.cpp
## VERSION: 1.0 
## SINCE 2015-10-23
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

class Solution {
public:
    int climbStairs(int n) {
        if (n <= 0) return 0;
        if (n == 1) return 1;
        if (n == 2) return 2; 
        vector<int> T(n+1, 0);
        T[1] = 1; 
        T[2] = 2;
        for (int i = 3; i < n+1; i ++)
            T[i] = T[i-1] + T[i-2];
        return T[n];
    }
};
