/*###############################################################
## MODULE: 075_SortColors.cpp
## VERSION: 1.0 
## SINCE 2015-10-23
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

class Solution {
public:
    void sortColors(vector<int>& nums) {
        vector<int> counters (3, 0);
        int n = nums.size();
        if (n == 0) return;
        for (int i = 0; i < n; i ++)
            counters[nums[i]] ++; 
        int b_0 = counters[0];
        int b_1 = b_0 + counters[1];
        int b_2 = b_1 + counters[2];
        for (int i = 0; i < n; i ++)
            if (i < b_0) nums[i] = 0;
            else if (i < b_1) nums[i] = 1;
            else if (i < b_2) nums[i] = 2;
    }
};
