/*###############################################################
## MODULE: 100_SameTree.cpp
## VERSION: 1.0 
## SINCE 2015-10-23
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
public:
    bool isSameTree(TreeNode* p, TreeNode* q) {
        if (p == NULL and q == NULL) return true;
        else if (p == NULL or q == NULL) return false;
        // take the case of p != NULL and q != NULL
        if (p->val != q->val) return false;
        else 
            return isSameTree(p->left, q->left) 
                && isSameTree(p->right, q->right);
    }
};
