/*###############################################################
## MODULE: 104_MaxDepthOfBinaryTree.cpp
## VERSION: 1.0 
## SINCE 2015-10-27
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
public:
    int maxDepth(TreeNode* root) {
        if (!root) return 0;
        if (!(root->left) and !(root->right))
            return 1;
        else if (!(root->left))
            return 1+maxDepth(root->right);
        else if (!(root->right))
            return 1+maxDepth(root->left);
        else return 1+max(maxDepth(root->left),maxDepth(root->right));
    }
};
