/*###############################################################
## MODULE: 111_MinimumDepthOfBinaryTree.cpp
## VERSION: 1.0 
## SINCE 2015-10-27
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Solution {
public:
    int minDepth(TreeNode* root) {
        if (root == NULL) return 0;
        if (root->left != NULL and root->right != NULL) 
            return 1+min(minDepth(root->left), minDepth(root->right));
        else if (root->left != NULL)
            return 1+minDepth(root->left);
        else if (root->right != NULL)
            return 1+minDepth(root->right);
        else return 1;
    }
};
