/*###############################################################
## MODULE: 219_ContainDuplicateII.cpp
## VERSION: 1.0 
## SINCE 2015-10-31
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

class Solution {
public:
    bool containsNearbyDuplicate(vector<int>& nums, int k) {
        int n = nums.size();
        if (n < 2) return false;
        unordered_map<int, int> map;
        for (int i = 0; i < n; i ++) 
            if (map.find(nums[i]) != map.end() and i - map[nums[i]] <= k) 
                return true; 
            else map[nums[i]] = i;
        return false;
    }
};
